### ISSUE TITLE
аутентификация по токену вместо логина и пароля (1000₽)

### ISSUE THREAD

**Issue by alex-mos** [alex-mos/mospan_pro_backend#1]
Сейчас бекенд-приложение на go, для того, чтобы отправлять почту мне на gmail, авторизуется в гугловом smtp-сервере моим логином и паролем от гугла.
Требуется заменить этот способ авторизации. Варианты:
1. заменить авторизацию по логину и паролю авторизацией по токену, созданному специально для этого приложения, с возможностью его инвалидации из панели управления гугла.
2. запустить отдельный почтовый сервер в контейнере на сервере, который будет отправлять почту независимо от моего гуглового аккаунта.

**Comment by maximal** [comment]
Самый главный вопрос: получатель будет один, или много? Посылать можно как через SMTP (если _O(n)_ получаетелей), так и локальным `sendmail`-ом (чаще в спаме, но если получателей _O(1)_, то норм).

**Comment by maximal** [comment]
В общем, отсылаем локальным SMTP. Как я понимаю, то, что иногда будет в спаме, не страшно. Несколько раз нажать [Не спам], и всё.
